package com.kama.jchatmind.trace;

public enum TraceEventType {
    RUN_STARTED,
    CONTEXT_BUILT,
    STEP_STARTED,
    MODEL_CALL_STARTED,
    MODEL_CALL_COMPLETED,
    MODEL_CALL_FAILED,
    MODEL_EMPTY_RESPONSE_RETRY,
    TOOL_CALL_STARTED,
    TOOL_CALL_COMPLETED,
    TOOL_CALL_FAILED,
    STEP_COMPLETED,
    RUN_COMPLETED,
    RUN_FAILED
}
